version: '3.8'

services:
  backend:
    build: .
    container_name: backend-tastemap
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SPRING_DATA_MONGODB_DATABASE=tastemap
    networks:
      - tastemap-net
    env_file:
      - .env

networks:
  tastemap-net: