spring.application.name=tastemap
# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.database=${DB_NAME}
spring.data.mongodb.uri=${DB_URI}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.main.allow-bean-definition-overriding=true
server.port=8080
server.address=0.0.0.0
spring.jackson.time-zone=America/Bogota
n8n.webhook.url=https://iabot-test-n8n.yuq1gm.easypanel.host/webhook-test/restaurant-cha