spring.application.name=tastemap

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.database=${DB_NAME}
spring.data.mongodb.uri=${DB_URI}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.main.allow-bean-definition-overriding=true
server.port=8080
server.address=0.0.0.0
spring.jackson.time-zone=America/Bogota
n8n.webhook.url=https://iabot-test-n8n.yuq1gm.easypanel.host/webhook/restaurant-chat
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME:logos}
azure.storage.menus-container-name=${AZURE_STORAGE_MENUS_CONTAINER:menus}
